[sites]
websites=   [
            "https://www.google.com",
            "http://localhost/Landing3/",
            "http://localhost/Landing3/"
            ]

alias=   [
            "Sitio de Google",
            "Sitio local",
            "Sitio local 2"
            ]

[email]
[email.server]
    server=""
    port=587
    login=""
    password=""
[email.config]
    sender=""
    to=""
    cc=""
    bcc=""
[email.build]
    subject="Cambio de estado WebSite "
    body="El siguiente sitio web se encuentra:  "

[general]
#Titulo principal.
titulo_principal="Web Site Monitor Tool"
#Tiempo en segundos entre pruebas.
tiempo_espera_entre_pruebas=3
#Tiempo en segundos por cada prueba antes de marcar una falla.
tiempo_espera_por_prueba=3
#Cuantas eventos iguales y seguidos disparan una notificacion (sitio caido o arriba).
cuantos_eventos_disparan=3
#Envia un correo si un sitio deja de responder en cuantos_eventos_disparan o se recupera y responde por cuantos_eventos_disparan.
enviar_correo=1
#Escribe en el log de eventos.
escribe_en_log_eventos=1
#Nombre del log de eventos.
nombre_log_eventos='websitealive.log'
#Zona Horaria en la que se esta midiendo el suceso.
zona_horaria='America/Bogota'
#Valida Certificados SSL (Si cuando todos los sitios tienen certificado, No para el caso de Hostnames o IPs)
validar_certificado=0

[tts]
#Lenguaje del Text to Speech (defecto es - English )
language_tts='en'
alert_tts='Alert, site has changed: '


[messages]
msg_up='up'
msg_down='down'


[info]
project="Website Alive"
author = "Pablo Castro"
version = "1.0.3"
date ="11 Sep 2021"