[sites]
websites=   [
            "https://www.google.com",
            "http://localhost/Landing3/"
            ]

[email]
[email.server]
    server=""
    port=587
    login=""
    password=""
[email.config]
    sender=""
    to=""
    cc=""
    bcc=""
[email.build]
    subject="Alert Site is  "
    body="Change state notification ==>  "

[general]
#Tiempo en segundos entre pruebas.
tiempo_espera_entre_pruebas=10
#Tiempo en segundos por cada prueba antes de marcar una falla.
tiempo_espera_por_prueba=3
#Cuantas eventos iguales y seguidos disparan una notificacion (sitio caido o arriba).
cuantos_eventos_disparan=10
#Envia un correo si un sitio deja de responder en cuantos_eventos_disparan o se recupera y responde por cuantos_eventos_disparan.
enviar_correo=1
#Escribe en el log de eventos.
escribe_en_log_eventos=1
#Nombre del log de eventos.
nombre_log_eventos='websitealive.log'
#Zona Horaria en la que se esta midiendo el suceso.
zona_horaria='America/Bogota'
#Muestra informacion por consola.
informacion_consola=1
#Valida Certificados SSL (Si cuando todos los sitios tienen certificado, No para el caso de Hostnames o IPs)
validar_certificado=0

[info]
project="Website Alive"
author = "Pablo Castro"
version = "1.0.3"
date ="11 Sep 2021"